[package]
name = "sklamini-kasir"
version = "1.4.0"
description = "Kasir TOKO SKLAMINI"
authors = ["TOKO SKLAMINI"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "sklamini_kasir_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
